"""add message_content to messages

Revision ID: 308506867505
Revises: c7835a84d3eb
Create Date: 2026-08-08 21:13:33.013705

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '308506867505'
down_revision: Union[str, Sequence[str], None] = 'c7835a84d3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_content')
    # ### end Alembic commands ###
