"""add chat requests

Revision ID: 33ab992720ad
Revises: 308506867505
Create Date: 2026-08-09 01:37:38.719692

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ab992720ad'
down_revision: Union[str, Sequence[str], None] = '308506867505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('chat_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chat_uid'], ['chats.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['chats.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_uid', 'user_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
