"""requests: surrogate uid

Revision ID: b1e88791f35b
Revises: f7650ee120ee
Create Date: 2026-08-09 02:41:04.677963

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1e88791f35b'
down_revision: Union[str, Sequence[str], None] = 'f7650ee120ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('uid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'requests', ['chat_uid', 'user_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='unique')
    op.drop_column('requests', 'uid')
    # ### end Alembic commands ###
