"""create db schema

Revision ID: c7835a84d3eb
Revises: 
Create Date: 2026-08-08 19:21:49.475083

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7835a84d3eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('owner_uid', sa.UUID(), nullable=True),
    sa.Column('chat_title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('chat_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('chat_user_link',
    sa.Column('chat_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_uid'], ['chats.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_uid', 'user_uid')
    )
    op.create_table('messages',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('chat_uid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chat_uid'], ['chats.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chat_user_link')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
